<HomeScreen>:
    statuslabel1: statuslabel1
    updatebutton: updatebutton
    loadbutton: loadbutton
    graphbutton: graphbutton
    toptenlabel: toptenlabel
            
    FloatLayout:
        canvas.before:
            Rectangle:
                pos: self.pos
                size: self.size
                source: 'COVID_Program/COVID Background.jpg'
                
        Label:
            id: welcomelabel
            bold: True
            color: 1,1,1,1
            text_size: self.size
            halign: 'center'
            valign: 'top'
            font_size: 22
            text: "\nCOVID DATA Program"
            
        Label: 
            id: statuslabel1
            bold: True
            color: 1,0,1,1
            text_size: self.size
            halign: 'left'
            valign: 'top'
            font_size: 16
            
        Label: 
            id: toptenlabel
            bold: True
            color: 1,0,1,1
            text_size: self.size
            halign: 'right'
            valign: 'top'
            font_size: 16
            
        Button: 
            id: updatebutton
            bold: True
            size_hint: .2,.06
            pos_hint: {'x': .4, 'y': .82}
            background_color: 0,0,1,.25
            color: 1,1,1,1
            text: "Update Database"
            on_release: root.update_thread()
            
        Button: 
            id: loadbutton
            bold: True
            size_hint: .2,.06
            pos_hint: {'x': .4, 'y': .75}
            background_color: 0,0,1,.25
            color: 1,1,1,1
            text: "Load Database"
            on_release: root.load_thread()
            
        Button: 
            id: graphbutton
            bold: True
            size_hint: .2,.06
            pos_hint: {'y': .68}
            background_color: 0,0,1,.25
            color: 1,1,1,1
            text: "Visualize Data"
            on_release: root.geo_viz()